package dev.jjcprogression.ct;

import dev.jjcprogression.config.ProgressionConfig;
import net.minecraft.server.level.ServerPlayer;
import net.minecraftforge.common.capabilities.Capability;
import java.lang.reflect.*;
import java.util.*;

/** JJC 50.1 technique IDs are verified against its Select*Procedure bytecode. */
public final class CursedTechniques {
    public enum Tier { C, B, A, S }
    public record Technique(String name, Tier tier, double id, String selector) {}
    private static Technique t(String n,Tier tier,double id,String selector){return new Technique(n,tier,id,selector);}
    private static final List<Technique> ALL=List.of(
      t("Mahoraga",Tier.S,16,"Mahoraga"),t("Gojo",Tier.S,2,"Gojo"),t("Sukuna",Tier.S,1,"Sukuna"),t("Geto",Tier.S,18,"Geto"),t("Tsukumo",Tier.S,9,"Tsukumo"),t("Yuta",Tier.S,5,"Okkotsu"),t("Maki",Tier.S,-1,"Maki"),t("Hakari",Tier.S,29,"Hakari"),t("Megumi",Tier.S,6,"Fushiguro"),t("Yuji",Tier.S,21,"Itadori"),t("Higuruma",Tier.S,27,"Higuruma"),
      t("Naoya",Tier.A,19,"Naoya"),t("Yaga",Tier.A,33,"Yaga"),t("Yorozu",Tier.A,39,"Yorozu"),t("Jogo",Tier.A,4,"Jogo"),t("Mahito",Tier.A,15,"Mahito"),t("Todo",Tier.A,20,"Todo"),t("Angel",Tier.A,28,"Angel"),t("Uraume",Tier.A,24,"Uraume"),t("Choso",Tier.A,10,"Choso"),t("Kashimo",Tier.A,7,"Kashimo"),t("Rozetsu",Tier.A,43,"Rozetsu"),
      t("Ino",Tier.B,40,"Ino"),t("Ogi",Tier.B,26,"Ogi"),t("Hanami",Tier.B,14,"Hanami"),t("Dagon",Tier.B,8,"Dagon"),t("Jinichi",Tier.B,22,"Jinichi"),t("Dhruv Lakdawalla",Tier.B,37,"DhruvLakdawalla"),t("Nanami",Tier.B,13,"Nanami"),t("Nobara",Tier.B,34,"Kugisaki"),t("Miguel",Tier.B,30,"Miguel"),t("Uro",Tier.B,38,"TakakoUro"),t("Reggie",Tier.B,44,"ReggieStar"),t("Crystal",Tier.B,47,"CrystalCurse"),
      t("Inumaki",Tier.C,3,"Inumaki"),t("Mei-Mei",Tier.C,11,"MeiMei"),t("Ishigori",Tier.C,12,"Ishigori"),t("Smallpox",Tier.C,25,"SmallpoxDeity"),t("Takaba",Tier.C,17,"Takaba"),t("Kurourushi",Tier.C,23,"Kurourushi"),t("Kusakabe",Tier.C,31,"Kusakabe"),t("Chojuro",Tier.C,32,"Chojuro"),t("Nishimiya",Tier.C,36,"Nishimiya"),t("Junpei",Tier.C,35,"Junpe"),t("Kaori",Tier.C,41,"Kaori"),t("Ranta",Tier.C,46,"Ranta"),t("Hazenoki",Tier.C,45,"Hazenoki"));
    private static final List<Technique> AVAILABLE=ALL.stream().filter(t->{boolean found=exists(t);if(!found)dev.jjcprogression.JJCProgression.LOGGER.warn("[JJCPROGRESSION] JJC technique selector is missing; excluding {} ({})",t.name(),t.selector());return found;}).toList();
    private CursedTechniques(){}
    public static List<Technique> all(){return AVAILABLE;}
    public static Optional<Technique> find(String name){return AVAILABLE.stream().filter(t->t.name.equalsIgnoreCase(name)||t.selector.equalsIgnoreCase(name)).findFirst();}
    public static Optional<Technique> current(ServerPlayer player){try{Object vars=variables(player);double id=vars.getClass().getField("PlayerCurseTechnique").getDouble(vars);return AVAILABLE.stream().filter(t->t.id==id).findFirst();}catch(ReflectiveOperationException|RuntimeException e){return Optional.empty();}}
    public static List<Technique> tier(Tier tier){return AVAILABLE.stream().filter(t->t.tier==tier).toList();}
    private static boolean exists(Technique t){try{Class.forName("net.mcreator.jujutsucraft.procedures.Select"+t.selector+"Procedure",false,CursedTechniques.class.getClassLoader());return true;}catch(ClassNotFoundException e){return false;}}
    public static Technique random(Tier tier){List<Technique> pool=tier(tier);if(pool.isEmpty())throw new IllegalStateException("No JJC selectors for tier "+tier);return pool.get(net.minecraft.util.RandomSource.create().nextInt(pool.size()));}
    public static int[] weights(String grade){return switch(grade){case "Grade 4"->new int[]{ProgressionConfig.G4_C.get(),ProgressionConfig.G4_B.get(),ProgressionConfig.G4_A.get(),ProgressionConfig.G4_S.get()};case "Grade 3"->new int[]{ProgressionConfig.G3_C.get(),ProgressionConfig.G3_B.get(),ProgressionConfig.G3_A.get(),ProgressionConfig.G3_S.get()};case "Semi Grade 2"->new int[]{ProgressionConfig.SG2_C.get(),ProgressionConfig.SG2_B.get(),ProgressionConfig.SG2_A.get(),ProgressionConfig.SG2_S.get()};case "Grade 2"->new int[]{ProgressionConfig.G2_C.get(),ProgressionConfig.G2_B.get(),ProgressionConfig.G2_A.get(),ProgressionConfig.G2_S.get()};case "Semi Grade 1"->new int[]{ProgressionConfig.SG1_C.get(),ProgressionConfig.SG1_B.get(),ProgressionConfig.SG1_A.get(),ProgressionConfig.SG1_S.get()};case "Grade 1"->new int[]{ProgressionConfig.G1_C.get(),ProgressionConfig.G1_B.get(),ProgressionConfig.G1_A.get(),ProgressionConfig.G1_S.get()};case "Special Grade"->new int[]{ProgressionConfig.SPECIAL_C.get(),ProgressionConfig.SPECIAL_B.get(),ProgressionConfig.SPECIAL_A.get(),ProgressionConfig.SPECIAL_S.get()};default->weights("Grade 4");};}
    public static Technique roll(String grade,int advancementCount){int[] w=weights(grade);int bonus=Math.min(ProgressionConfig.CT_ADVANCEMENT_MAX_BPS.get(),Math.max(0,advancementCount)*ProgressionConfig.CT_ADVANCEMENT_BONUS_BPS.get());if(!grade.equals("Grade 4")){int moved=Math.min(w[0],bonus*2);w[0]-=moved;w[2]+=Math.min(bonus,moved);w[3]+=Math.max(0,moved-bonus);}if(grade.equals("Grade 4")){w[2]=0;w[3]=0;}if(grade.equals("Special Grade")){w[0]=0;w[1]=0;}return rollWeights(w,grade);}
    public static Technique rollFirst(){return rollWeights(new int[]{ProgressionConfig.FIRST_C.get(),ProgressionConfig.FIRST_B.get(),ProgressionConfig.FIRST_A.get(),ProgressionConfig.FIRST_S.get()},"first roll");}
    private static Technique rollWeights(int[] w,String label){int total=Arrays.stream(w).sum();if(total<=0)throw new IllegalStateException("CT weights sum to zero for "+label);int x=net.minecraft.util.RandomSource.create().nextInt(total);Tier chosen=Tier.C;for(Tier tier:new Tier[]{Tier.C,Tier.B,Tier.A,Tier.S}){int n=w[tier.ordinal()];if(x<n){chosen=tier;break;}x-=n;}return random(chosen);}
    public static void assign(ServerPlayer player,Technique t){set(player,t.id,t.name);}
    public static void clear(ServerPlayer player){set(player,0.0,"");}
    public static void resetJjcProgress(ServerPlayer player,Technique t){
        try{Object vars=variables(player);Class<?> c=vars.getClass();for(String n:new String[]{"PlayerCursePower","PlayerCursePowerChange","PlayerCursePowerFormer","PlayerExperience","PlayerLevel","PlayerFame","PlayerProfession","PlayerCurseTechnique2","PlayerSelectCurseTechnique","PlayerSelectCurseTechniqueCost","PlayerSelectCurseTechniqueCostOrgin"})c.getField(n).setDouble(vars,0.0);c.getField("PlayerCursePowerMAX").setDouble(vars,10.0);c.getField("PlayerCurseTechnique").setDouble(vars,t.id);c.getField("PlayerSelectCurseTechniqueName").set(vars,t.name);c.getField("SecondTechnique").setBoolean(vars,false);c.getField("FlagSixEyes").setBoolean(vars,false);c.getMethod("syncPlayerVariables",net.minecraft.world.entity.Entity.class).invoke(vars,player);}catch(ReflectiveOperationException|RuntimeException ex){throw new IllegalStateException("Could not reset JJC 50.1 progression",ex);}
    }
    public static void applyCursedEnergyInvestment(ServerPlayer player,int investment){try{Object vars=variables(player);Class<?> c=vars.getClass();Field max=c.getField("PlayerCursePowerMAX"),current=c.getField("PlayerCursePower");double newMax=10.0+Math.min(ProgressionConfig.CE_MAX_BONUS.get(),Math.max(0,investment)*ProgressionConfig.CE_PER_POINT.get());max.setDouble(vars,newMax);current.setDouble(vars,Math.min(Math.max(0.0,current.getDouble(vars)),newMax));c.getMethod("syncPlayerVariables",net.minecraft.world.entity.Entity.class).invoke(vars,player);}catch(ReflectiveOperationException|RuntimeException ignored){/* Optional CE scaling fails closed; JJC remains in control. */}}
    private static Object variables(ServerPlayer player)throws ReflectiveOperationException{Class<?> api=Class.forName("net.mcreator.jujutsucraft.network.JujutsucraftModVariables");@SuppressWarnings("unchecked") Capability<Object> cap=(Capability<Object>)api.getField("PLAYER_VARIABLES_CAPABILITY").get(null);return player.getCapability(cap).resolve().orElseThrow(()->new IllegalStateException("JJC player capability unavailable"));}
    private static void set(ServerPlayer player,double id,String name){try{Class<?> api=Class.forName("net.mcreator.jujutsucraft.network.JujutsucraftModVariables");@SuppressWarnings("unchecked") Capability<Object> cap=(Capability<Object>)api.getField("PLAYER_VARIABLES_CAPABILITY").get(null);Object vars=player.getCapability(cap).resolve().orElseThrow();vars.getClass().getField("PlayerCurseTechnique").setDouble(vars,id);vars.getClass().getField("PlayerSelectCurseTechniqueName").set(vars,name);vars.getClass().getMethod("syncPlayerVariables",net.minecraft.world.entity.Entity.class).invoke(vars,player);}catch(ReflectiveOperationException|RuntimeException ex){throw new IllegalStateException("JJC 50.1 technique capability unavailable",ex);}}
}
